//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidato()
        {
            this.Cuestionario = new HashSet<Cuestionario>();
            this.Evaluacion = new HashSet<Evaluacion>();
        }
    
        public int nroCandidato { get; set; }
        public string nro_documento { get; set; }
        public string tipo_documento { get; set; }
        public string contraseña { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string genero { get; set; }
        public string nacionalidad { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string email { get; set; }
        public int escolaridad { get; set; }
        public string id_consultor { get; set; }
        public Nullable<System.DateTime> fecha_eliminado { get; set; }
    
        public virtual Consultor Consultor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuestionario> Cuestionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
    }
}
