//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuestionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuestionario()
        {
            this.Bloque = new HashSet<Bloque>();
            this.Estado_Cuestionario = new HashSet<Estado_Cuestionario>();
            this.LogProcesos = new HashSet<LogProcesos>();
        }
    
        public int id_cuestionario { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public int cantidad_accesos { get; set; }
        public Nullable<System.DateTime> ultimo_acceso { get; set; }
        public int nroCandidato { get; set; }
        public Nullable<int> id_evaluacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bloque> Bloque { get; set; }
        public virtual Candidato Candidato { get; set; }
        public virtual Evaluacion Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_Cuestionario> Estado_Cuestionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogProcesos> LogProcesos { get; set; }
    }
}
