//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado_Cuestionario
    {
        public int id_estado { get; set; }
        public System.DateTime fecha_mod { get; set; }
        public string estadoAnterior { get; set; }
        public string estadoActual { get; set; }
        public int id_cuestionario { get; set; }
    
        public virtual Cuestionario Cuestionario { get; set; }
    }
}
