//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factor()
        {
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int codigo_factor { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public int nro_orden { get; set; }
        public int codigo_competencia { get; set; }
        public Nullable<System.DateTime> fecha_eliminado { get; set; }
        public Nullable<int> id_consultor { get; set; }
    
        public virtual Competencia Competencia { get; set; }
        public virtual Consultor Consultor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregunta> Pregunta { get; set; }

        public bool Equals(Factor fac)
        {
            return (this.codigo_competencia == fac.codigo_competencia && this.codigo_factor == fac.codigo_factor && this.nombre == fac.nombre && this.nro_orden == fac.nro_orden && this.estado == fac.estado && this.descripcion == fac.descripcion);
        }
    }
}
