//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBloque
    {
        public int id_bloque { get; set; }
        public int id_pregunta { get; set; }
        public Nullable<int> id_respuesta { get; set; }
    
        public virtual Bloque Bloque { get; set; }
        public virtual Pregunta Pregunta { get; set; }
        public virtual Respuesta Respuesta { get; set; }
    }
}
