//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogProcesos
    {
        public int id_log_proceso { get; set; }
        public System.DateTime fechaHora { get; set; }
        public string accion { get; set; }
        public int id_cuestionario { get; set; }
    
        public virtual Cuestionario Cuestionario { get; set; }
    }
}
