//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregunta()
        {
            this.RespuestaElegida = new HashSet<RespuestaElegida>();
            this.ValorRespuesta = new HashSet<ValorRespuesta>();
        }
    
        public int id_pregunta { get; set; }
        public string descripcion { get; set; }
        public string interrogante { get; set; }
        public string nombre { get; set; }
        public int codigo_factor { get; set; }
        public Nullable<int> id_consultor { get; set; }
        public Nullable<System.DateTime> fecha_eliminado { get; set; }
        public int id_opcion_respuesta { get; set; }
    
        public virtual Consultor Consultor { get; set; }
        public virtual Factor Factor { get; set; }
        public virtual OpcionRespuesta OpcionRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaElegida> RespuestaElegida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValorRespuesta> ValorRespuesta { get; set; }
    }
}
