//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puesto()
        {
            this.Puntaje_Requerido = new HashSet<Puntaje_Requerido>();
        }
    
        public int id_puesto { get; set; }
        public int codigo_puesto { get; set; }
        public System.DateTime fecha_ultima_modificacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string empresa { get; set; }
        public Nullable<int> id_consultor { get; set; }
        public Nullable<System.DateTime> fecha_eliminado { get; set; }
    
        public virtual Consultor Consultor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puntaje_Requerido> Puntaje_Requerido { get; set; }

        public Puesto(int cod, string nom, string desc, string emp, List<Puntaje_Requerido> listCar)
        {
            codigo_puesto = cod;
            nombre = nom;
            descripcion = desc;
            empresa = emp;
            Puntaje_Requerido = listCar;
        }
    }
}
