//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puesto()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
            this.Puntaje_Requerido = new HashSet<Puntaje_Requerido>();
        }
    
        public int id_puesto { get; set; }
        public int codigo_puesto { get; set; }
        public Nullable<System.DateTime> fecha_ultima_modificacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string empresa { get; set; }
        public string id_consultor { get; set; }
        public Nullable<System.DateTime> fecha_eliminado { get; set; }
    
        public virtual Consultor Consultor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puntaje_Requerido> Puntaje_Requerido { get; set; }

        public Puesto(int cod, string nom, string desc, string emp, List<Puntaje_Requerido> listaCar)
        {
            this.codigo_puesto = cod;
            this.nombre = nom;
            this.descripcion = desc;
            this.empresa = emp;
            this.Puntaje_Requerido = listaCar;
            this.estado = "Activo";
            this.fecha_ultima_modificacion = DateTime.Now;
        }
    }
}
