//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntaje_Requerido
    {
        public int id_puesto { get; set; }
        public int codigo_competencia { get; set; }
        public int ponderacion { get; set; }
    
        public virtual Competencia Competencia { get; set; }
        public virtual Puesto Puesto { get; set; }

        public Puntaje_Requerido() { }

        public Puntaje_Requerido(Competencia comp, int pond)
        {
            this.codigo_competencia = comp.id_competencia;
            this.ponderacion = pond;
        }

        public bool Igual(Puntaje_Requerido pr)
        {
            return (this.codigo_competencia == pr.codigo_competencia && this.ponderacion == pr.ponderacion);
        }
    }
}
